# Sponsorship Information
# This Code of Conduct template is sponsored by Toilville
# We're available to help with community management and Code of Conduct implementation

custom: ["https://www.itstoilville.com/", "https://www.itstoilville.com/services/"]
